### PR TITLE
APP-56: Add setup.py

### PR DESCRIPTION
**Pull request by AlpyneDreams**
This should make setup a lot easier. See the README

### CODE REVIEW

**Comment by mruiz42** [comment]
Can we get some windows user to verify this works before merging? @Like-Home/full-stack-developers

**Review by Zariphron — APPROVED** [review]
Confirms the run.js file works on windows, no issues with python versions

**Comment by mruiz42** [comment]
Mine stopped running here:
```
 python3 setup.py
Looking for Python 3.11...
Trying 'py -3.11'
Trying 'py'
Trying 'python3.11'
```
Traceback:
```
^CTraceback (most recent call last):
  File "/Users/michael/WebstormProjects/LikeHome/setup.py", line 38, in <module>
    py = find_python()
         ^^^^^^^^^^^^^
  File "/Users/michael/WebstormProjects/LikeHome/setup.py", line 25, in find_python
    version = run(exe + " --version")
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michael/WebstormProjects/LikeHome/setup.py", line 8, in run
    out, err = proc.communicate()
               ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1207, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 2059, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
``` 
Python 3.11.2 on MacOS

Maybe Noah has better luck here? @NoahCardoza

**Comment by RishiJ12** [comment]
Yo when running python setup.py I ran into this error: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 in position 162: invalid start byte

**Comment by mruiz42** [comment]
> Yo when running python setup.py I ran into this error: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 in position 162: invalid start byte

Could possibly be because Windows uses UTF-16 encoding by default. Not sure without more debug info tho.
Also, what unicode is being processed in setup.py that would be causing this error @AlpyneDreams ?

**Comment by NoahCardoza** [comment]
We tried UTF-16 but no luck. It happened when running Poetry install if I remember correctly. Probably from the loading animating or something...

**Comment by mruiz42** [comment]
> We tried UTF-16 but no luck. It happened when running Poetry install if I remember correctly. Probably from the loading animating or something...
Good point, I would also guess it would be the downloading animations.
Would using `--quiet` option be a good workaround here?
https://python-poetry.org/docs/cli/

**Comment by NoahCardoza** [comment]
@mruiz42 Good idea. Could you test on a fresh clone on Windows? I don't have a Windows machine to test on...

**Comment by AlpyneDreams** [comment]
> Good point, I would also guess it would be the downloading animations now that you've narrowed it down. Would using an option such as `--ansi` or `--quiet` be a good workaround here? @AlpyneDreams @NoahCardoza https://python-poetry.org/docs/cli/


Pushed a fix with `--quiet`

**Review by NoahCardoza — APPROVED** [review]
LGTM! Works on my Mac.

**Pull request merged**
